version: '3'
services:
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    restart: on-failure

  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:
    build: ./todo-app/tests
    restart: on-failure
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
